# Generated by Django 4.1.1 on 2023-07-18 19:29

from django.db import migrations, models
import django.db.models.deletion
import laboratorio.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "f_fabricacion",
                    models.IntegerField(
                        choices=[
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                        ],
                        default=laboratorio.models.anno_actual,
                    ),
                ),
                ("p_costo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("p_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "laboratorio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laboratorio.laboratorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectorGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255)),
                (
                    "laboratorio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratorio.laboratorio",
                    ),
                ),
            ],
        ),
    ]
