# Generated by Django 4.1.1 on 2023-07-18 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("laboratorio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorgeneral",
            name="especialidad",
            field=models.CharField(default="administrador de empresas", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laboratorio",
            name="ciudad",
            field=models.CharField(default="Concepcion", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laboratorio",
            name="pais",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
